batch_size: 32
dataset_path: E:\Backup\Dataset
height: 96
learning_rate: 0.001
max_text_length: 77
model_path: Models\yaml
train_epochs: 15
train_workers: 20
vocab: abcdefghijklmnopqrstuvwxyz0123456789,;.!?:'"/\|_@#$%^&*~`+-=<>()[]\{\} ABCDEFGHIJKLMNOPQRSTUVWXYZ
width: 1408
working_dir: E:\Backup\FinalProjectML\ml-project-handwritten-text-recognition
