batch_size: 32
dataset_path: E:\Backup\Dataset
height: 96
learning_rate: 0.001
max_text_length: 77
model_path: Models\yaml2
train_epochs: 20
train_workers: 20
vocab: 'cQjNm:gka5uU7I6tF)Kh3JnOilA2w9WCRxydVe #!qfLrPHBs,1Eo''v"GD4Y;?.(Sb0&MZp8T-z'
width: 1408
working_dir: E:\Backup\FinalProjectML\ml-project-handwritten-text-recognition
