batch_size: 32
height: 96
learning_rate: 0.001
max_text_length: 77
model_path: Models\yaml2
train_epochs: 20
train_workers: 20
vocab: 'pWJ&TU3If8-kl.1PMqK E?LvwN9Czu!Qe#a(4,Y;6FgZGo''0sV"SROAbHxd)iyBhDnrj27mc5t:'
width: 1408
