batch_size: 32
dataset_path: E:\Backup\Dataset
height: 96
learning_rate: 0.001
max_text_length: 77
model_path: Models\yaml2
train_epochs: 20
train_workers: 20
vocab: '#Eu(5Alqgz4WJMx:?iPkT8KfLU2h&!ISQtRd7Cn;Z)9YDeBFo sryOc,"vj''1Hm0.w-p3NaGV6b'
width: 1408
working_dir: E:\Backup\FinalProjectML\ml-project-handwritten-text-recognition
